name: minimeet
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0
  auto_route: ^5.0.4
  device_preview: ^1.1.0
  
  path_provider: ^2.0.11
  google_maps_flutter: ^2.5.0
  firebase_core: ^2.16.0
  google_sign_in: ^6.1.5 
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.10.0
  flutter_carousel_slider: ^1.0.2
  carousel_slider: ^4.2.1
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/ 